/*** Compiler Front-End Test automatically generated by the BNF Converter ***/
/*                                                                          */
/* This test will parse a file, print the abstract syntax tree, and then    */
/* pretty-print the result.                                                 */
/*                                                                          */
/****************************************************************************/
#include <stdio.h>
#include "Parser.H"
#include "Printer.H"
#include "Absyn.H"
#include "SymbolTable.H"
#include "Symbol.H"
#include "Logger.H"
#include "InstructionVisitor.H"
#include "Stdfunc.H"
#include "Codegen.H"

int main(int argc, char ** argv) {
    FILE *input;
    if (argc > 1) {
        input = fopen(argv[1], "r");
        if (!input) {
            fprintf(stderr, "Error opening input file.\n");
            exit(1);
        }
    } else input = stdin;
    /* The default entry point is used. For other options see Parser.H */
    Prog *parse_tree = pProg(input);
//  printf("Parsing finished\n");
    if (parse_tree) {
        SymbolTable<std::string, JSymbol> st;
        Logger logger;
        populateSymbolTable(st);
        InstructionVisitor iv(st, logger);
        parse_tree->accept(&iv);
        if (logger.anyFatalErrors()) return 1;
//      printf("\nParse Succesful!\n");
//      printf("\n[Abstract Syntax]\n");
//      ShowAbsyn *s = new ShowAbsyn();
//      printf("%s\n\n", s->show(parse_tree));
//      printf("[Linearized Tree]\n");
//      PrintAbsyn *p = new PrintAbsyn();
//      printf("%s\n\n", p->print(parse_tree));
        Generator gen;
        parse_tree->genCode(&gen);
        return 0;
    }
    return 1;
}

