//C++ Abstract Syntax Implementation generated by the BNF Converter.
#include <algorithm>
#include <string>
#include <iostream>
#include <vector>
#include "Absyn.H"
/********************   Program    ********************/
Program::Program(ListFunDef *p1)
{
  listfundef_ = p1;

}

Program::Program(const Program & other)
{
  listfundef_ = other.listfundef_->clone();

}

Program &Program::operator=(const Program & other)
{
  Program tmp(other);
  swap(tmp);
  return *this;
}

void Program::swap(Program & other)
{
  std::swap(listfundef_, other.listfundef_);

}

Program::~Program()
{
  delete(listfundef_);

}

llvm::Value* Program::genCode(CodeGeneratorVisitor* v) {
    return v->visitProgram(this);
}

void Program::accept(Visitor *v)
{
  v->visitProgram(this);
}

Program *Program::clone() const
{
  return new Program(*this);
}



/********************   Function    ********************/
Function::Function(Type *p1, Ident p2, ListArg *p3, Instr *p4)
{
  type_ = p1;
  ident_ = p2;
  listarg_ = p3;
  instr_ = p4;

}

Function::Function(const Function & other)
{
  type_ = other.type_->clone();
  ident_ = other.ident_;
  listarg_ = other.listarg_->clone();
  instr_ = other.instr_->clone();

}

Function &Function::operator=(const Function & other)
{
  Function tmp(other);
  swap(tmp);
  return *this;
}

void Function::swap(Function & other)
{
  std::swap(type_, other.type_);
  std::swap(ident_, other.ident_);
  std::swap(listarg_, other.listarg_);
  std::swap(instr_, other.instr_);

}

Function::~Function()
{
  delete(type_);
  delete(listarg_);
  delete(instr_);

}

llvm::Value* Function::genCode(CodeGeneratorVisitor* v) {
    return v->visitFunction(this);
}

void Function::accept(Visitor *v)
{
  v->visitFunction(this);
}

Function *Function::clone() const
{
  return new Function(*this);
}



/********************   IntType    ********************/
IntType::IntType()
{

}

IntType::IntType(const IntType & other)
{

}

IntType &IntType::operator=(const IntType & other)
{
  IntType tmp(other);
  swap(tmp);
  return *this;
}

void IntType::swap(IntType & other)
{

}

JType* IntType::getJType() const {
  return new JInt();
}

const llvm::Type* IntType::getLLVMType() const
{
  return llvm::Type::Int32Ty;
}

IntType::~IntType()
{

}

llvm::Value* IntType::genCode(CodeGeneratorVisitor* v) {
    return v->visitIntType(this);
}

void IntType::accept(Visitor *v)
{
  v->visitIntType(this);
}

IntType *IntType::clone() const
{
  return new IntType(*this);
}



/********************   DoubleType    ********************/
DoubleType::DoubleType()
{

}

DoubleType::DoubleType(const DoubleType & other)
{

}

DoubleType &DoubleType::operator=(const DoubleType & other)
{
  DoubleType tmp(other);
  swap(tmp);
  return *this;
}

void DoubleType::swap(DoubleType & other)
{

}

JType* DoubleType::getJType() const {
  return new JDouble();
}

const llvm::Type* DoubleType::getLLVMType() const
{
  return llvm::Type::DoubleTy;
}

DoubleType::~DoubleType()
{

}

llvm::Value* DoubleType::genCode(CodeGeneratorVisitor* v) {
    return v->visitDoubleType(this);
}

void DoubleType::accept(Visitor *v)
{
  v->visitDoubleType(this);
}

DoubleType *DoubleType::clone() const
{
  return new DoubleType(*this);
}



/********************   VoidType    ********************/
VoidType::VoidType()
{

}

VoidType::VoidType(const VoidType & other)
{

}

VoidType &VoidType::operator=(const VoidType & other)
{
  VoidType tmp(other);
  swap(tmp);
  return *this;
}

void VoidType::swap(VoidType & other)
{

}

JType* VoidType::getJType() const {
  return new JVoid();
}

const llvm::Type* VoidType::getLLVMType() const
{
  return llvm::Type::VoidTy;
}

VoidType::~VoidType()
{

}

llvm::Value* VoidType::genCode(CodeGeneratorVisitor* v) {
    return v->visitVoidType(this);
}

void VoidType::accept(Visitor *v)
{
  v->visitVoidType(this);
}

VoidType *VoidType::clone() const
{
  return new VoidType(*this);
}



/********************   BoolType    ********************/
BoolType::BoolType()
{

}

BoolType::BoolType(const BoolType & other)
{

}

BoolType &BoolType::operator=(const BoolType & other)
{
  BoolType tmp(other);
  swap(tmp);
  return *this;
}

void BoolType::swap(BoolType & other)
{

}

JType* BoolType::getJType() const {
  return new JBool();
}

const llvm::Type* BoolType::getLLVMType() const
{
  return llvm::Type::Int1Ty;
}

BoolType::~BoolType()
{

}

llvm::Value* BoolType::genCode(CodeGeneratorVisitor* v) {
    return v->visitBoolType(this);
}

void BoolType::accept(Visitor *v)
{
  v->visitBoolType(this);
}

BoolType *BoolType::clone() const
{
  return new BoolType(*this);
}



/********************   FunctionArg    ********************/
FunctionArg::FunctionArg(Type *p1, Ident p2)
{
  type_ = p1;
  ident_ = p2;

}

FunctionArg::FunctionArg(const FunctionArg & other)
{
  type_ = other.type_->clone();
  ident_ = other.ident_;

}

FunctionArg &FunctionArg::operator=(const FunctionArg & other)
{
  FunctionArg tmp(other);
  swap(tmp);
  return *this;
}

void FunctionArg::swap(FunctionArg & other)
{
  std::swap(type_, other.type_);
  std::swap(ident_, other.ident_);

}

FunctionArg::~FunctionArg()
{
  delete(type_);

}

llvm::Value* FunctionArg::genCode(CodeGeneratorVisitor* v) {
    return v->visitFunctionArg(this);
}

void FunctionArg::accept(Visitor *v)
{
  v->visitFunctionArg(this);
}

FunctionArg *FunctionArg::clone() const
{
  return new FunctionArg(*this);
}



/********************   CompoundInstr    ********************/
CompoundInstr::CompoundInstr(ListInstr *p1)
{
  listinstr_ = p1;

}

CompoundInstr::CompoundInstr(const CompoundInstr & other)
{
  listinstr_ = other.listinstr_->clone();

}

CompoundInstr &CompoundInstr::operator=(const CompoundInstr & other)
{
  CompoundInstr tmp(other);
  swap(tmp);
  return *this;
}

void CompoundInstr::swap(CompoundInstr & other)
{
  std::swap(listinstr_, other.listinstr_);

}

CompoundInstr::~CompoundInstr()
{
  delete(listinstr_);

}

llvm::Value* CompoundInstr::genCode(CodeGeneratorVisitor* v) {
    return v->visitCompoundInstr(this);
}

void CompoundInstr::accept(Visitor *v)
{
  v->visitCompoundInstr(this);
}

CompoundInstr *CompoundInstr::clone() const
{
  return new CompoundInstr(*this);
}



/********************   InnerFunction    ********************/
InnerFunction::InnerFunction(FunDef *p1)
{
  fundef_ = p1;

}

InnerFunction::InnerFunction(const InnerFunction & other)
{
  fundef_ = other.fundef_->clone();

}

InnerFunction &InnerFunction::operator=(const InnerFunction & other)
{
  InnerFunction tmp(other);
  swap(tmp);
  return *this;
}

void InnerFunction::swap(InnerFunction & other)
{
  std::swap(fundef_, other.fundef_);

}

InnerFunction::~InnerFunction()
{
  delete(fundef_);

}

llvm::Value* InnerFunction::genCode(CodeGeneratorVisitor* v) {
    return v->visitInnerFunction(this);
}

void InnerFunction::accept(Visitor *v)
{
  v->visitInnerFunction(this);
}

InnerFunction *InnerFunction::clone() const
{
  return new InnerFunction(*this);
}



/********************   ReturnInstr    ********************/
ReturnInstr::ReturnInstr()
{

}

ReturnInstr::ReturnInstr(const ReturnInstr & other)
{

}

ReturnInstr &ReturnInstr::operator=(const ReturnInstr & other)
{
  ReturnInstr tmp(other);
  swap(tmp);
  return *this;
}

void ReturnInstr::swap(ReturnInstr & other)
{

}

ReturnInstr::~ReturnInstr()
{

}

llvm::Value* ReturnInstr::genCode(CodeGeneratorVisitor* v) {
    return v->visitReturnInstr(this);
}

void ReturnInstr::accept(Visitor *v)
{
  v->visitReturnInstr(this);
}

ReturnInstr *ReturnInstr::clone() const
{
  return new ReturnInstr(*this);
}



/********************   ReturnExprInstr    ********************/
ReturnExprInstr::ReturnExprInstr(Expr *p1)
{
  expr_ = p1;

}

ReturnExprInstr::ReturnExprInstr(const ReturnExprInstr & other)
{
  expr_ = other.expr_->clone();

}

ReturnExprInstr &ReturnExprInstr::operator=(const ReturnExprInstr & other)
{
  ReturnExprInstr tmp(other);
  swap(tmp);
  return *this;
}

void ReturnExprInstr::swap(ReturnExprInstr & other)
{
  std::swap(expr_, other.expr_);

}

ReturnExprInstr::~ReturnExprInstr()
{
  delete(expr_);

}

llvm::Value* ReturnExprInstr::genCode(CodeGeneratorVisitor* v) {
    return v->visitReturnExprInstr(this);
}

void ReturnExprInstr::accept(Visitor *v)
{
  v->visitReturnExprInstr(this);
}

ReturnExprInstr *ReturnExprInstr::clone() const
{
  return new ReturnExprInstr(*this);
}



/********************   DeclInstr    ********************/
DeclInstr::DeclInstr(Type *p1, ListDecl *p2)
{
  type_ = p1;
  listdecl_ = p2;

}

DeclInstr::DeclInstr(const DeclInstr & other)
{
  type_ = other.type_->clone();
  listdecl_ = other.listdecl_->clone();

}

DeclInstr &DeclInstr::operator=(const DeclInstr & other)
{
  DeclInstr tmp(other);
  swap(tmp);
  return *this;
}

void DeclInstr::swap(DeclInstr & other)
{
  std::swap(type_, other.type_);
  std::swap(listdecl_, other.listdecl_);

}

DeclInstr::~DeclInstr()
{
  delete(type_);
  delete(listdecl_);

}

llvm::Value* DeclInstr::genCode(CodeGeneratorVisitor* v) {
    return v->visitDeclInstr(this);
}

void DeclInstr::accept(Visitor *v)
{
  v->visitDeclInstr(this);
}

DeclInstr *DeclInstr::clone() const
{
  return new DeclInstr(*this);
}



/********************   ConditionalIf    ********************/
ConditionalIf::ConditionalIf(Expr *p1, Instr *p2)
{
  expr_ = p1;
  instr_ = p2;

}

ConditionalIf::ConditionalIf(const ConditionalIf & other)
{
  expr_ = other.expr_->clone();
  instr_ = other.instr_->clone();

}

ConditionalIf &ConditionalIf::operator=(const ConditionalIf & other)
{
  ConditionalIf tmp(other);
  swap(tmp);
  return *this;
}

void ConditionalIf::swap(ConditionalIf & other)
{
  std::swap(expr_, other.expr_);
  std::swap(instr_, other.instr_);

}

ConditionalIf::~ConditionalIf()
{
  delete(expr_);
  delete(instr_);

}

llvm::Value* ConditionalIf::genCode(CodeGeneratorVisitor* v) {
    return v->visitConditionalIf(this);
}

void ConditionalIf::accept(Visitor *v)
{
  v->visitConditionalIf(this);
}

ConditionalIf *ConditionalIf::clone() const
{
  return new ConditionalIf(*this);
}



/********************   ConditionalIfElse    ********************/
ConditionalIfElse::ConditionalIfElse(Expr *p1, Instr *p2, Instr *p3)
{
  expr_ = p1;
  instr_1 = p2;
  instr_2 = p3;

}

ConditionalIfElse::ConditionalIfElse(const ConditionalIfElse & other)
{
  expr_ = other.expr_->clone();
  instr_1 = other.instr_1->clone();
  instr_2 = other.instr_2->clone();

}

ConditionalIfElse &ConditionalIfElse::operator=(const ConditionalIfElse & other)
{
  ConditionalIfElse tmp(other);
  swap(tmp);
  return *this;
}

void ConditionalIfElse::swap(ConditionalIfElse & other)
{
  std::swap(expr_, other.expr_);
  std::swap(instr_1, other.instr_1);
  std::swap(instr_2, other.instr_2);

}

ConditionalIfElse::~ConditionalIfElse()
{
  delete(expr_);
  delete(instr_1);
  delete(instr_2);

}

llvm::Value* ConditionalIfElse::genCode(CodeGeneratorVisitor* v) {
    return v->visitConditionalIfElse(this);
}

void ConditionalIfElse::accept(Visitor *v)
{
  v->visitConditionalIfElse(this);
}

ConditionalIfElse *ConditionalIfElse::clone() const
{
  return new ConditionalIfElse(*this);
}



/********************   ExpressionInstr    ********************/
ExpressionInstr::ExpressionInstr(Expr *p1)
{
  expr_ = p1;

}

ExpressionInstr::ExpressionInstr(const ExpressionInstr & other)
{
  expr_ = other.expr_->clone();

}

ExpressionInstr &ExpressionInstr::operator=(const ExpressionInstr & other)
{
  ExpressionInstr tmp(other);
  swap(tmp);
  return *this;
}

void ExpressionInstr::swap(ExpressionInstr & other)
{
  std::swap(expr_, other.expr_);

}

ExpressionInstr::~ExpressionInstr()
{
  delete(expr_);

}

llvm::Value* ExpressionInstr::genCode(CodeGeneratorVisitor* v) {
    return v->visitExpressionInstr(this);
}

void ExpressionInstr::accept(Visitor *v)
{
  v->visitExpressionInstr(this);
}

ExpressionInstr *ExpressionInstr::clone() const
{
  return new ExpressionInstr(*this);
}



/********************   ForLoop    ********************/
ForLoop::ForLoop(ListExpr *p1, ListExpr *p2, ListExpr *p3, Instr *p4)
{
  listexpr_1 = p1;
  listexpr_2 = p2;
  listexpr_3 = p3;
  instr_ = p4;

}

ForLoop::ForLoop(const ForLoop & other)
{
  listexpr_1 = other.listexpr_1->clone();
  listexpr_2 = other.listexpr_2->clone();
  listexpr_3 = other.listexpr_3->clone();
  instr_ = other.instr_->clone();

}

ForLoop &ForLoop::operator=(const ForLoop & other)
{
  ForLoop tmp(other);
  swap(tmp);
  return *this;
}

void ForLoop::swap(ForLoop & other)
{
  std::swap(listexpr_1, other.listexpr_1);
  std::swap(listexpr_2, other.listexpr_2);
  std::swap(listexpr_3, other.listexpr_3);
  std::swap(instr_, other.instr_);

}

ForLoop::~ForLoop()
{
  delete(listexpr_1);
  delete(listexpr_2);
  delete(listexpr_3);
  delete(instr_);

}

llvm::Value* ForLoop::genCode(CodeGeneratorVisitor* v) {
    return v->visitForLoop(this);
}

void ForLoop::accept(Visitor *v)
{
  v->visitForLoop(this);
}

ForLoop *ForLoop::clone() const
{
  return new ForLoop(*this);
}



/********************   WhileLoop    ********************/
WhileLoop::WhileLoop(Expr *p1, Instr *p2)
{
  expr_ = p1;
  instr_ = p2;

}

WhileLoop::WhileLoop(const WhileLoop & other)
{
  expr_ = other.expr_->clone();
  instr_ = other.instr_->clone();

}

WhileLoop &WhileLoop::operator=(const WhileLoop & other)
{
  WhileLoop tmp(other);
  swap(tmp);
  return *this;
}

void WhileLoop::swap(WhileLoop & other)
{
  std::swap(expr_, other.expr_);
  std::swap(instr_, other.instr_);

}

WhileLoop::~WhileLoop()
{
  delete(expr_);
  delete(instr_);

}

llvm::Value* WhileLoop::genCode(CodeGeneratorVisitor* v) {
    return v->visitWhileLoop(this);
}

void WhileLoop::accept(Visitor *v)
{
  v->visitWhileLoop(this);
}

WhileLoop *WhileLoop::clone() const
{
  return new WhileLoop(*this);
}



/********************   OnlyDeclarator    ********************/
OnlyDeclarator::OnlyDeclarator(Ident p1)
{
  ident_ = p1;

}

OnlyDeclarator::OnlyDeclarator(const OnlyDeclarator & other)
{
  ident_ = other.ident_;

}

OnlyDeclarator &OnlyDeclarator::operator=(const OnlyDeclarator & other)
{
  OnlyDeclarator tmp(other);
  swap(tmp);
  return *this;
}

void OnlyDeclarator::swap(OnlyDeclarator & other)
{
  std::swap(ident_, other.ident_);

}

OnlyDeclarator::~OnlyDeclarator()
{

}

llvm::Value* OnlyDeclarator::genCodeWithType(const llvm::Type *type, CodeGeneratorVisitor *v) {
    return v->visitOnlyDeclarator(type, this);
}

void OnlyDeclarator::accept(Visitor *v)
{
  v->visitOnlyDeclarator(this);
}

OnlyDeclarator *OnlyDeclarator::clone() const
{
  return new OnlyDeclarator(*this);
}


llvm::Value* OnlyDeclarator::genCode(CodeGeneratorVisitor *v) {
    std::cerr << "ERRPR this code shouldn't ever run " << __FILE__ << " " << __LINE__ << std::endl;
    return NULL;
}

/********************   InitDeclarator    ********************/
InitDeclarator::InitDeclarator(Ident p1, Expr *p2)
{
  ident_ = p1;
  expr_ = p2;

}

InitDeclarator::InitDeclarator(const InitDeclarator & other)
{
  ident_ = other.ident_;
  expr_ = other.expr_->clone();

}

InitDeclarator &InitDeclarator::operator=(const InitDeclarator & other)
{
  InitDeclarator tmp(other);
  swap(tmp);
  return *this;
}

void InitDeclarator::swap(InitDeclarator & other)
{
  std::swap(ident_, other.ident_);
  std::swap(expr_, other.expr_);

}

InitDeclarator::~InitDeclarator()
{
  delete(expr_);

}

llvm::Value* InitDeclarator::genCodeWithType(const llvm::Type *type, CodeGeneratorVisitor *v) {
    return v->visitInitDeclarator(type, this);
}

void InitDeclarator::accept(Visitor *v)
{
  v->visitInitDeclarator(this);
}

InitDeclarator *InitDeclarator::clone() const
{
  return new InitDeclarator(*this);
}


llvm::Value* InitDeclarator::genCode(CodeGeneratorVisitor *v) {
    std::cerr << "ERRPR this code shouldn't ever run " << __FILE__ << " " << __LINE__ << std::endl;
    return NULL;
}


/********************   ArrayDeclarator    ********************/
ArrayDeclarator::ArrayDeclarator(Ident p1, Expr *p2)
{
  ident_ = p1;
  expr_ = p2;

}

ArrayDeclarator::ArrayDeclarator(const ArrayDeclarator & other)
{
  ident_ = other.ident_;
  expr_ = other.expr_->clone();

}

ArrayDeclarator &ArrayDeclarator::operator=(const ArrayDeclarator & other)
{
  ArrayDeclarator tmp(other);
  swap(tmp);
  return *this;
}

void ArrayDeclarator::swap(ArrayDeclarator & other)
{
  std::swap(ident_, other.ident_);
  std::swap(expr_, other.expr_);

}

ArrayDeclarator::~ArrayDeclarator()
{
  delete(expr_);

}

llvm::Value* ArrayDeclarator::genCodeWithType(const llvm::Type *type, CodeGeneratorVisitor *v) {
    return v->visitArrayDeclarator(type, this);
}

llvm::Value* ArrayDeclarator::genCode(CodeGeneratorVisitor *v) {
    std::cerr << "ERRPR this code shouldn't ever run " << __FILE__ << " " << __LINE__ << std::endl;
    return NULL;
}

void ArrayDeclarator::accept(Visitor *v)
{
  v->visitArrayDeclarator(this);
}

ArrayDeclarator *ArrayDeclarator::clone() const
{
  return new ArrayDeclarator(*this);
}



/********************   IdentAssigment    ********************/
IdentAssigment::IdentAssigment(Ident p1, Expr *p2)
{
  ident_ = p1;
  expr_ = p2;

}

IdentAssigment::IdentAssigment(const IdentAssigment & other)
{
  ident_ = other.ident_;
  expr_ = other.expr_->clone();

}

IdentAssigment &IdentAssigment::operator=(const IdentAssigment & other)
{
  IdentAssigment tmp(other);
  swap(tmp);
  return *this;
}

void IdentAssigment::swap(IdentAssigment & other)
{
  std::swap(ident_, other.ident_);
  std::swap(expr_, other.expr_);

}

IdentAssigment::~IdentAssigment()
{
  delete(expr_);

}

llvm::Value* IdentAssigment::genCode(CodeGeneratorVisitor* v) {
    return v->visitIdentAssigment(this);
}

void IdentAssigment::accept(Visitor *v)
{
  v->visitIdentAssigment(this);
}

IdentAssigment *IdentAssigment::clone() const
{
  return new IdentAssigment(*this);
}



/********************   ArrayAssigment    ********************/
ArrayAssigment::ArrayAssigment(Ident p1, Expr *p2, Expr *p3)
{
  ident_ = p1;
  expr_1 = p2;
  expr_2 = p3;

}

ArrayAssigment::ArrayAssigment(const ArrayAssigment & other)
{
  ident_ = other.ident_;
  expr_1 = other.expr_1->clone();
  expr_2 = other.expr_2->clone();

}

ArrayAssigment &ArrayAssigment::operator=(const ArrayAssigment & other)
{
  ArrayAssigment tmp(other);
  swap(tmp);
  return *this;
}

void ArrayAssigment::swap(ArrayAssigment & other)
{
  std::swap(ident_, other.ident_);
  std::swap(expr_1, other.expr_1);
  std::swap(expr_2, other.expr_2);

}

ArrayAssigment::~ArrayAssigment()
{
  delete(expr_1);
  delete(expr_2);

}

llvm::Value* ArrayAssigment::genCode(CodeGeneratorVisitor* v) {
    return v->visitArrayAssigment(this);
}

void ArrayAssigment::accept(Visitor *v)
{
  v->visitArrayAssigment(this);
}

ArrayAssigment *ArrayAssigment::clone() const
{
  return new ArrayAssigment(*this);
}



/********************   PostDecrement    ********************/
PostDecrement::PostDecrement(Ident p1)
{
  ident_ = p1;

}

PostDecrement::PostDecrement(const PostDecrement & other)
{
  ident_ = other.ident_;

}

PostDecrement &PostDecrement::operator=(const PostDecrement & other)
{
  PostDecrement tmp(other);
  swap(tmp);
  return *this;
}

void PostDecrement::swap(PostDecrement & other)
{
  std::swap(ident_, other.ident_);

}

PostDecrement::~PostDecrement()
{

}

llvm::Value* PostDecrement::genCode(CodeGeneratorVisitor* v) {
    return v->visitPostDecrement(this);
}

void PostDecrement::accept(Visitor *v)
{
  v->visitPostDecrement(this);
}

PostDecrement *PostDecrement::clone() const
{
  return new PostDecrement(*this);
}



/********************   PostIncrement    ********************/
PostIncrement::PostIncrement(Ident p1)
{
  ident_ = p1;

}

PostIncrement::PostIncrement(const PostIncrement & other)
{
  ident_ = other.ident_;

}

PostIncrement &PostIncrement::operator=(const PostIncrement & other)
{
  PostIncrement tmp(other);
  swap(tmp);
  return *this;
}

void PostIncrement::swap(PostIncrement & other)
{
  std::swap(ident_, other.ident_);

}

PostIncrement::~PostIncrement()
{

}

llvm::Value* PostIncrement::genCode(CodeGeneratorVisitor* v) {
    return v->visitPostIncrement(this);
}

void PostIncrement::accept(Visitor *v)
{
  v->visitPostIncrement(this);
}

PostIncrement *PostIncrement::clone() const
{
  return new PostIncrement(*this);
}



/********************   Cast    ********************/
Cast::Cast(Type *p1, Expr *p2)
{
  type_ = p1;
  expr_ = p2;

}

Cast::Cast(const Cast & other)
{
  type_ = other.type_->clone();
  expr_ = other.expr_->clone();

}

Cast &Cast::operator=(const Cast & other)
{
  Cast tmp(other);
  swap(tmp);
  return *this;
}

void Cast::swap(Cast & other)
{
  std::swap(type_, other.type_);
  std::swap(expr_, other.expr_);

}

Cast::~Cast()
{
  delete(type_);
  delete(expr_);

}

llvm::Value* Cast::genCode(CodeGeneratorVisitor* v) {
    return v->visitCast(this);
}

void Cast::accept(Visitor *v)
{
  v->visitCast(this);
}

Cast *Cast::clone() const
{
  return new Cast(*this);
}



/********************   LogExprOr    ********************/
LogExprOr::LogExprOr(Expr *p1, Expr *p2)
{
  expr_1 = p1;
  expr_2 = p2;

}

LogExprOr::LogExprOr(const LogExprOr & other)
{
  expr_1 = other.expr_1->clone();
  expr_2 = other.expr_2->clone();

}

LogExprOr &LogExprOr::operator=(const LogExprOr & other)
{
  LogExprOr tmp(other);
  swap(tmp);
  return *this;
}

void LogExprOr::swap(LogExprOr & other)
{
  std::swap(expr_1, other.expr_1);
  std::swap(expr_2, other.expr_2);

}

LogExprOr::~LogExprOr()
{
  delete(expr_1);
  delete(expr_2);

}

llvm::Value* LogExprOr::genCode(CodeGeneratorVisitor* v) {
    return v->visitLogExprOr(this);
}

void LogExprOr::accept(Visitor *v)
{
  v->visitLogExprOr(this);
}

LogExprOr *LogExprOr::clone() const
{
  return new LogExprOr(*this);
}



/********************   LogExprAnd    ********************/
LogExprAnd::LogExprAnd(Expr *p1, Expr *p2)
{
  expr_1 = p1;
  expr_2 = p2;

}

LogExprAnd::LogExprAnd(const LogExprAnd & other)
{
  expr_1 = other.expr_1->clone();
  expr_2 = other.expr_2->clone();

}

LogExprAnd &LogExprAnd::operator=(const LogExprAnd & other)
{
  LogExprAnd tmp(other);
  swap(tmp);
  return *this;
}

void LogExprAnd::swap(LogExprAnd & other)
{
  std::swap(expr_1, other.expr_1);
  std::swap(expr_2, other.expr_2);

}

LogExprAnd::~LogExprAnd()
{
  delete(expr_1);
  delete(expr_2);

}

llvm::Value* LogExprAnd::genCode(CodeGeneratorVisitor* v) {
    return v->visitLogExprAnd(this);
}

void LogExprAnd::accept(Visitor *v)
{
  v->visitLogExprAnd(this);
}

LogExprAnd *LogExprAnd::clone() const
{
  return new LogExprAnd(*this);
}



/********************   LogExprEq    ********************/
LogExprEq::LogExprEq(Expr *p1, Expr *p2)
{
  expr_1 = p1;
  expr_2 = p2;

}

LogExprEq::LogExprEq(const LogExprEq & other)
{
  expr_1 = other.expr_1->clone();
  expr_2 = other.expr_2->clone();

}

LogExprEq &LogExprEq::operator=(const LogExprEq & other)
{
  LogExprEq tmp(other);
  swap(tmp);
  return *this;
}

void LogExprEq::swap(LogExprEq & other)
{
  std::swap(expr_1, other.expr_1);
  std::swap(expr_2, other.expr_2);

}

LogExprEq::~LogExprEq()
{
  delete(expr_1);
  delete(expr_2);

}

llvm::Value* LogExprEq::genCode(CodeGeneratorVisitor* v) {
    return v->visitLogExprEq(this);
}

void LogExprEq::accept(Visitor *v)
{
  v->visitLogExprEq(this);
}

LogExprEq *LogExprEq::clone() const
{
  return new LogExprEq(*this);
}



/********************   LogExprNeq    ********************/
LogExprNeq::LogExprNeq(Expr *p1, Expr *p2)
{
  expr_1 = p1;
  expr_2 = p2;

}

LogExprNeq::LogExprNeq(const LogExprNeq & other)
{
  expr_1 = other.expr_1->clone();
  expr_2 = other.expr_2->clone();

}

LogExprNeq &LogExprNeq::operator=(const LogExprNeq & other)
{
  LogExprNeq tmp(other);
  swap(tmp);
  return *this;
}

void LogExprNeq::swap(LogExprNeq & other)
{
  std::swap(expr_1, other.expr_1);
  std::swap(expr_2, other.expr_2);

}

LogExprNeq::~LogExprNeq()
{
  delete(expr_1);
  delete(expr_2);

}

llvm::Value* LogExprNeq::genCode(CodeGeneratorVisitor* v) {
    return v->visitLogExprNeq(this);
}

void LogExprNeq::accept(Visitor *v)
{
  v->visitLogExprNeq(this);
}

LogExprNeq *LogExprNeq::clone() const
{
  return new LogExprNeq(*this);
}



/********************   RelExprL    ********************/
RelExprL::RelExprL(Expr *p1, Expr *p2)
{
  expr_1 = p1;
  expr_2 = p2;

}

RelExprL::RelExprL(const RelExprL & other)
{
  expr_1 = other.expr_1->clone();
  expr_2 = other.expr_2->clone();

}

RelExprL &RelExprL::operator=(const RelExprL & other)
{
  RelExprL tmp(other);
  swap(tmp);
  return *this;
}

void RelExprL::swap(RelExprL & other)
{
  std::swap(expr_1, other.expr_1);
  std::swap(expr_2, other.expr_2);

}

RelExprL::~RelExprL()
{
  delete(expr_1);
  delete(expr_2);

}

llvm::Value* RelExprL::genCode(CodeGeneratorVisitor* v) {
    return v->visitRelExprL(this);
}

void RelExprL::accept(Visitor *v)
{
  v->visitRelExprL(this);
}

RelExprL *RelExprL::clone() const
{
  return new RelExprL(*this);
}



/********************   RelExprG    ********************/
RelExprG::RelExprG(Expr *p1, Expr *p2)
{
  expr_1 = p1;
  expr_2 = p2;

}

RelExprG::RelExprG(const RelExprG & other)
{
  expr_1 = other.expr_1->clone();
  expr_2 = other.expr_2->clone();

}

RelExprG &RelExprG::operator=(const RelExprG & other)
{
  RelExprG tmp(other);
  swap(tmp);
  return *this;
}

void RelExprG::swap(RelExprG & other)
{
  std::swap(expr_1, other.expr_1);
  std::swap(expr_2, other.expr_2);

}

RelExprG::~RelExprG()
{
  delete(expr_1);
  delete(expr_2);

}

llvm::Value* RelExprG::genCode(CodeGeneratorVisitor* v) {
    return v->visitRelExprG(this);
}

void RelExprG::accept(Visitor *v)
{
  v->visitRelExprG(this);
}

RelExprG *RelExprG::clone() const
{
  return new RelExprG(*this);
}



/********************   RelExprLe    ********************/
RelExprLe::RelExprLe(Expr *p1, Expr *p2)
{
  expr_1 = p1;
  expr_2 = p2;

}

RelExprLe::RelExprLe(const RelExprLe & other)
{
  expr_1 = other.expr_1->clone();
  expr_2 = other.expr_2->clone();

}

RelExprLe &RelExprLe::operator=(const RelExprLe & other)
{
  RelExprLe tmp(other);
  swap(tmp);
  return *this;
}

void RelExprLe::swap(RelExprLe & other)
{
  std::swap(expr_1, other.expr_1);
  std::swap(expr_2, other.expr_2);

}

RelExprLe::~RelExprLe()
{
  delete(expr_1);
  delete(expr_2);

}

llvm::Value* RelExprLe::genCode(CodeGeneratorVisitor* v) {
    return v->visitRelExprLe(this);
}

void RelExprLe::accept(Visitor *v)
{
  v->visitRelExprLe(this);
}

RelExprLe *RelExprLe::clone() const
{
  return new RelExprLe(*this);
}



/********************   RelExprGe    ********************/
RelExprGe::RelExprGe(Expr *p1, Expr *p2)
{
  expr_1 = p1;
  expr_2 = p2;

}

RelExprGe::RelExprGe(const RelExprGe & other)
{
  expr_1 = other.expr_1->clone();
  expr_2 = other.expr_2->clone();

}

RelExprGe &RelExprGe::operator=(const RelExprGe & other)
{
  RelExprGe tmp(other);
  swap(tmp);
  return *this;
}

void RelExprGe::swap(RelExprGe & other)
{
  std::swap(expr_1, other.expr_1);
  std::swap(expr_2, other.expr_2);

}

RelExprGe::~RelExprGe()
{
  delete(expr_1);
  delete(expr_2);

}

llvm::Value* RelExprGe::genCode(CodeGeneratorVisitor* v) {
    return v->visitRelExprGe(this);
}

void RelExprGe::accept(Visitor *v)
{
  v->visitRelExprGe(this);
}

RelExprGe *RelExprGe::clone() const
{
  return new RelExprGe(*this);
}



/********************   AddExpr    ********************/
AddExpr::AddExpr(Expr *p1, Expr *p2)
{
  expr_1 = p1;
  expr_2 = p2;

}

AddExpr::AddExpr(const AddExpr & other)
{
  expr_1 = other.expr_1->clone();
  expr_2 = other.expr_2->clone();

}

AddExpr &AddExpr::operator=(const AddExpr & other)
{
  AddExpr tmp(other);
  swap(tmp);
  return *this;
}

void AddExpr::swap(AddExpr & other)
{
  std::swap(expr_1, other.expr_1);
  std::swap(expr_2, other.expr_2);

}

AddExpr::~AddExpr()
{
  delete(expr_1);
  delete(expr_2);

}

llvm::Value* AddExpr::genCode(CodeGeneratorVisitor* v) {
    return v->visitAddExpr(this);
}

void AddExpr::accept(Visitor *v)
{
  v->visitAddExpr(this);
}

AddExpr *AddExpr::clone() const
{
  return new AddExpr(*this);
}



/********************   DecExpr    ********************/
DecExpr::DecExpr(Expr *p1, Expr *p2)
{
  expr_1 = p1;
  expr_2 = p2;

}

DecExpr::DecExpr(const DecExpr & other)
{
  expr_1 = other.expr_1->clone();
  expr_2 = other.expr_2->clone();

}

DecExpr &DecExpr::operator=(const DecExpr & other)
{
  DecExpr tmp(other);
  swap(tmp);
  return *this;
}

void DecExpr::swap(DecExpr & other)
{
  std::swap(expr_1, other.expr_1);
  std::swap(expr_2, other.expr_2);

}

DecExpr::~DecExpr()
{
  delete(expr_1);
  delete(expr_2);

}

llvm::Value* DecExpr::genCode(CodeGeneratorVisitor* v) {
    return v->visitDecExpr(this);
}

void DecExpr::accept(Visitor *v)
{
  v->visitDecExpr(this);
}

DecExpr *DecExpr::clone() const
{
  return new DecExpr(*this);
}



/********************   MulExpr    ********************/
MulExpr::MulExpr(Expr *p1, Expr *p2)
{
  expr_1 = p1;
  expr_2 = p2;

}

MulExpr::MulExpr(const MulExpr & other)
{
  expr_1 = other.expr_1->clone();
  expr_2 = other.expr_2->clone();

}

MulExpr &MulExpr::operator=(const MulExpr & other)
{
  MulExpr tmp(other);
  swap(tmp);
  return *this;
}

void MulExpr::swap(MulExpr & other)
{
  std::swap(expr_1, other.expr_1);
  std::swap(expr_2, other.expr_2);

}

MulExpr::~MulExpr()
{
  delete(expr_1);
  delete(expr_2);

}

llvm::Value* MulExpr::genCode(CodeGeneratorVisitor* v) {
    return v->visitMulExpr(this);
}

void MulExpr::accept(Visitor *v)
{
  v->visitMulExpr(this);
}

MulExpr *MulExpr::clone() const
{
  return new MulExpr(*this);
}



/********************   DivExpr    ********************/
DivExpr::DivExpr(Expr *p1, Expr *p2)
{
  expr_1 = p1;
  expr_2 = p2;

}

DivExpr::DivExpr(const DivExpr & other)
{
  expr_1 = other.expr_1->clone();
  expr_2 = other.expr_2->clone();

}

DivExpr &DivExpr::operator=(const DivExpr & other)
{
  DivExpr tmp(other);
  swap(tmp);
  return *this;
}

void DivExpr::swap(DivExpr & other)
{
  std::swap(expr_1, other.expr_1);
  std::swap(expr_2, other.expr_2);

}

DivExpr::~DivExpr()
{
  delete(expr_1);
  delete(expr_2);

}

llvm::Value* DivExpr::genCode(CodeGeneratorVisitor* v) {
    return v->visitDivExpr(this);
}

void DivExpr::accept(Visitor *v)
{
  v->visitDivExpr(this);
}

DivExpr *DivExpr::clone() const
{
  return new DivExpr(*this);
}



/********************   ModExpr    ********************/
ModExpr::ModExpr(Expr *p1, Expr *p2)
{
  expr_1 = p1;
  expr_2 = p2;

}

ModExpr::ModExpr(const ModExpr & other)
{
  expr_1 = other.expr_1->clone();
  expr_2 = other.expr_2->clone();

}

ModExpr &ModExpr::operator=(const ModExpr & other)
{
  ModExpr tmp(other);
  swap(tmp);
  return *this;
}

void ModExpr::swap(ModExpr & other)
{
  std::swap(expr_1, other.expr_1);
  std::swap(expr_2, other.expr_2);

}

ModExpr::~ModExpr()
{
  delete(expr_1);
  delete(expr_2);

}

llvm::Value* ModExpr::genCode(CodeGeneratorVisitor* v) {
    return v->visitModExpr(this);
}

void ModExpr::accept(Visitor *v)
{
  v->visitModExpr(this);
}

ModExpr *ModExpr::clone() const
{
  return new ModExpr(*this);
}



/********************   NegExpr    ********************/
NegExpr::NegExpr(Expr *p1)
{
  expr_ = p1;

}

NegExpr::NegExpr(const NegExpr & other)
{
  expr_ = other.expr_->clone();

}

NegExpr &NegExpr::operator=(const NegExpr & other)
{
  NegExpr tmp(other);
  swap(tmp);
  return *this;
}

void NegExpr::swap(NegExpr & other)
{
  std::swap(expr_, other.expr_);

}

NegExpr::~NegExpr()
{
  delete(expr_);

}

llvm::Value* NegExpr::genCode(CodeGeneratorVisitor* v) {
    return v->visitNegExpr(this);
}

void NegExpr::accept(Visitor *v)
{
  v->visitNegExpr(this);
}

NegExpr *NegExpr::clone() const
{
  return new NegExpr(*this);
}



/********************   PlusExpr    ********************/
PlusExpr::PlusExpr(Expr *p1)
{
  expr_ = p1;

}

PlusExpr::PlusExpr(const PlusExpr & other)
{
  expr_ = other.expr_->clone();

}

PlusExpr &PlusExpr::operator=(const PlusExpr & other)
{
  PlusExpr tmp(other);
  swap(tmp);
  return *this;
}

void PlusExpr::swap(PlusExpr & other)
{
  std::swap(expr_, other.expr_);

}

PlusExpr::~PlusExpr()
{
  delete(expr_);

}

llvm::Value* PlusExpr::genCode(CodeGeneratorVisitor* v) {
    return v->visitPlusExpr(this);
}

void PlusExpr::accept(Visitor *v)
{
  v->visitPlusExpr(this);
}

PlusExpr *PlusExpr::clone() const
{
  return new PlusExpr(*this);
}



/********************   MinusExpr    ********************/
MinusExpr::MinusExpr(Expr *p1)
{
  expr_ = p1;

}

MinusExpr::MinusExpr(const MinusExpr & other)
{
  expr_ = other.expr_->clone();

}

MinusExpr &MinusExpr::operator=(const MinusExpr & other)
{
  MinusExpr tmp(other);
  swap(tmp);
  return *this;
}

void MinusExpr::swap(MinusExpr & other)
{
  std::swap(expr_, other.expr_);

}

MinusExpr::~MinusExpr()
{
  delete(expr_);

}

llvm::Value* MinusExpr::genCode(CodeGeneratorVisitor* v) {
    return v->visitMinusExpr(this);
}

void MinusExpr::accept(Visitor *v)
{
  v->visitMinusExpr(this);
}

MinusExpr *MinusExpr::clone() const
{
  return new MinusExpr(*this);
}



/********************   FunctionCall    ********************/
FunctionCall::FunctionCall(Ident p1, ListExpr *p2)
{
  ident_ = p1;
  listexpr_ = p2;

}

FunctionCall::FunctionCall(const FunctionCall & other)
{
  ident_ = other.ident_;
  listexpr_ = other.listexpr_->clone();

}

FunctionCall &FunctionCall::operator=(const FunctionCall & other)
{
  FunctionCall tmp(other);
  swap(tmp);
  return *this;
}

void FunctionCall::swap(FunctionCall & other)
{
  std::swap(ident_, other.ident_);
  std::swap(listexpr_, other.listexpr_);

}

FunctionCall::~FunctionCall()
{
  delete(listexpr_);

}

llvm::Value* FunctionCall::genCode(CodeGeneratorVisitor* v) {
    return v->visitFunctionCall(this);
}

void FunctionCall::accept(Visitor *v)
{
  v->visitFunctionCall(this);
}

FunctionCall *FunctionCall::clone() const
{
  return new FunctionCall(*this);
}



/********************   ArrayAccess    ********************/
ArrayAccess::ArrayAccess(Ident p1, Expr *p2)
{
  ident_ = p1;
  expr_ = p2;

}

ArrayAccess::ArrayAccess(const ArrayAccess & other)
{
  ident_ = other.ident_;
  expr_ = other.expr_->clone();

}

ArrayAccess &ArrayAccess::operator=(const ArrayAccess & other)
{
  ArrayAccess tmp(other);
  swap(tmp);
  return *this;
}

void ArrayAccess::swap(ArrayAccess & other)
{
  std::swap(ident_, other.ident_);
  std::swap(expr_, other.expr_);

}

ArrayAccess::~ArrayAccess()
{
  delete(expr_);

}

llvm::Value* ArrayAccess::genCode(CodeGeneratorVisitor* v) {
    return v->visitArrayAccess(this);
}

void ArrayAccess::accept(Visitor *v)
{
  v->visitArrayAccess(this);
}

ArrayAccess *ArrayAccess::clone() const
{
  return new ArrayAccess(*this);
}



/********************   IdentExpr    ********************/
IdentExpr::IdentExpr(Ident p1)
{
  ident_ = p1;

}

IdentExpr::IdentExpr(const IdentExpr & other)
{
  ident_ = other.ident_;

}

IdentExpr &IdentExpr::operator=(const IdentExpr & other)
{
  IdentExpr tmp(other);
  swap(tmp);
  return *this;
}

void IdentExpr::swap(IdentExpr & other)
{
  std::swap(ident_, other.ident_);

}

IdentExpr::~IdentExpr()
{

}

llvm::Value* IdentExpr::genCode(CodeGeneratorVisitor* v) {
    return v->visitIdentExpr(this);
}

void IdentExpr::accept(Visitor *v)
{
  v->visitIdentExpr(this);
}

IdentExpr *IdentExpr::clone() const
{
  return new IdentExpr(*this);
}



/********************   LiteralExpr    ********************/
LiteralExpr::LiteralExpr(Literal *p1)
{
  literal_ = p1;

}

LiteralExpr::LiteralExpr(const LiteralExpr & other)
{
  literal_ = other.literal_->clone();

}

LiteralExpr &LiteralExpr::operator=(const LiteralExpr & other)
{
  LiteralExpr tmp(other);
  swap(tmp);
  return *this;
}

void LiteralExpr::swap(LiteralExpr & other)
{
  std::swap(literal_, other.literal_);

}

LiteralExpr::~LiteralExpr()
{
  delete(literal_);

}

llvm::Value* LiteralExpr::genCode(CodeGeneratorVisitor* v) {
    return v->visitLiteralExpr(this);
}

void LiteralExpr::accept(Visitor *v)
{
  v->visitLiteralExpr(this);
}

LiteralExpr *LiteralExpr::clone() const
{
  return new LiteralExpr(*this);
}



/********************   LiteralInteger    ********************/
LiteralInteger::LiteralInteger(Integer p1)
{
  integer_ = p1;

}

LiteralInteger::LiteralInteger(const LiteralInteger & other)
{
  integer_ = other.integer_;

}

LiteralInteger &LiteralInteger::operator=(const LiteralInteger & other)
{
  LiteralInteger tmp(other);
  swap(tmp);
  return *this;
}

void LiteralInteger::swap(LiteralInteger & other)
{
  std::swap(integer_, other.integer_);

}

LiteralInteger::~LiteralInteger()
{

}

llvm::Value* LiteralInteger::genCode(CodeGeneratorVisitor* v) {
    return v->visitLiteralInteger(this);
}

void LiteralInteger::accept(Visitor *v)
{
  v->visitLiteralInteger(this);
}

LiteralInteger *LiteralInteger::clone() const
{
  return new LiteralInteger(*this);
}



/********************   LiteralDouble    ********************/
LiteralDouble::LiteralDouble(Double p1)
{
  double_ = p1;

}

LiteralDouble::LiteralDouble(const LiteralDouble & other)
{
  double_ = other.double_;

}

LiteralDouble &LiteralDouble::operator=(const LiteralDouble & other)
{
  LiteralDouble tmp(other);
  swap(tmp);
  return *this;
}

void LiteralDouble::swap(LiteralDouble & other)
{
  std::swap(double_, other.double_);

}

LiteralDouble::~LiteralDouble()
{

}

llvm::Value* LiteralDouble::genCode(CodeGeneratorVisitor* v) {
    return v->visitLiteralDouble(this);
}

void LiteralDouble::accept(Visitor *v)
{
  v->visitLiteralDouble(this);
}

LiteralDouble *LiteralDouble::clone() const
{
  return new LiteralDouble(*this);
}



/********************   LiteralString    ********************/
LiteralString::LiteralString(String p1)
{
  string_ = p1;

}

LiteralString::LiteralString(const LiteralString & other)
{
  string_ = other.string_;

}

LiteralString &LiteralString::operator=(const LiteralString & other)
{
  LiteralString tmp(other);
  swap(tmp);
  return *this;
}

void LiteralString::swap(LiteralString & other)
{
  std::swap(string_, other.string_);

}

LiteralString::~LiteralString()
{

}

llvm::Value* LiteralString::genCode(CodeGeneratorVisitor* v) {
    return v->visitLiteralString(this);
}

void LiteralString::accept(Visitor *v)
{
  v->visitLiteralString(this);
}

LiteralString *LiteralString::clone() const
{
  return new LiteralString(*this);
}



/********************   LiteralBoolean    ********************/
LiteralBoolean::LiteralBoolean(Boolean p1)
{
  boolean_ = p1;

}

LiteralBoolean::LiteralBoolean(const LiteralBoolean & other)
{
  boolean_ = other.boolean_;

}

LiteralBoolean &LiteralBoolean::operator=(const LiteralBoolean & other)
{
  LiteralBoolean tmp(other);
  swap(tmp);
  return *this;
}

void LiteralBoolean::swap(LiteralBoolean & other)
{
  std::swap(boolean_, other.boolean_);

}

LiteralBoolean::~LiteralBoolean()
{

}

llvm::Value* LiteralBoolean::genCode(CodeGeneratorVisitor* v) {
    return v->visitLiteralBoolean(this);
}

void LiteralBoolean::accept(Visitor *v)
{
  v->visitLiteralBoolean(this);
}

LiteralBoolean *LiteralBoolean::clone() const
{
  return new LiteralBoolean(*this);
}




/********************   ListFunDef    ********************/

llvm::Value* ListFunDef::genCode(CodeGeneratorVisitor* v) {
    return v->visitListFunDef(this);
}

void ListFunDef::accept(Visitor *v)
{
  v->visitListFunDef(this);
}


ListFunDef *ListFunDef::clone() const
{
  return new ListFunDef(*this);
}


/********************   ListArg    ********************/

llvm::Value* ListArg::genCode(CodeGeneratorVisitor* v) {
    return v->visitListArg(this);
}

void ListArg::accept(Visitor *v)
{
  v->visitListArg(this);
}


ListArg *ListArg::clone() const
{
  return new ListArg(*this);
}


/********************   ListInstr    ********************/

llvm::Value* ListInstr::genCode(CodeGeneratorVisitor* v) {
    return v->visitListInstr(this);
}

void ListInstr::accept(Visitor *v)
{
  v->visitListInstr(this);
}


ListInstr *ListInstr::clone() const
{
  return new ListInstr(*this);
}


/********************   ListDecl    ********************/

llvm::Value* ListDecl::genCodeWithType(const llvm::Type* type, CodeGeneratorVisitor* v) {
    return v->visitListDecl(type, this);
}

void ListDecl::accept(Visitor *v)
{
  v->visitListDecl(this);
}


ListDecl *ListDecl::clone() const
{
  return new ListDecl(*this);
}

llvm::Value* ListDecl::genCode(CodeGeneratorVisitor *v) {
    std::cerr << "ERRPR this code shouldn't ever run " << __FILE__ << " " << __LINE__ << std::endl;
    return NULL;
}

/********************   ListExpr    ********************/

llvm::Value* ListExpr::genCode(CodeGeneratorVisitor* v) {
    return v->visitListExpr(this);
}

void ListExpr::accept(Visitor *v)
{
  v->visitListExpr(this);
}


ListExpr *ListExpr::clone() const
{
  return new ListExpr(*this);
}



